name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Create or Update Comment
  uses: peter-evans/create-or-update-comment@v1.0.0
  with:
    # GITHUB_TOKEN or a repo scoped PAT.
    token: 
    # The full name of the repository in which to create or update a comment.
    repository: # optional
    # The number of the issue or pull request in which to create a comment.
    issue-number: # optional
    # The id of the comment to update.
    comment-id: # optional
    # The comment body.
    body: # optional
    # The mode when updating a comment, "replace" or "append".
    edit-mode: # optional
    # The reaction to add to the comment.
    reaction-type
